#! @bash@/bin/sh -e

shopt -s nullglob

export PATH=/empty:@path@

usage() {
    echo "usage: $0 -t <timeout> -c <path-to-default-configuration> [-d <boot-dir>] [-g <num-generations>]" >&2
    exit 1
}

timeout=5
default=
target=/boot
numGenerations=0

while getopts "t:c:d:g:" opt; do
    case "$opt" in
        t)
            if [ "$OPTARG" -lt 0 ]; then
                timeout=0
            else
                timeout="$OPTARG"
            fi
            ;;
        c) default="$OPTARG" ;;
        d) target="$OPTARG" ;;
        g) numGenerations="$OPTARG" ;;
        \?) usage ;;
    esac
done

[ "$default" = "" ] && usage

mkdir -p $target/nixos

# Convert a path to a file in the Nix store such as
# /nix/store/<hash>-<name>/file to <hash>-<name>-<file>.
cleanName() {
    local path="$1"
    echo "$path" | sed 's|^/nix/store/||' | sed 's|/|-|g'
}

# Copy a file from the Nix store to $target/nixos.
declare -A filesCopied

copyToKernelsDir() {
    local src=$(readlink -f "$1")
    local dst="$target/nixos/$(cleanName $src)"
    if ! test -e $dst; then
        local dstTmp=$dst.tmp.$$
        cp -r $src $dstTmp
        mv $dstTmp $dst
    fi
    filesCopied[$dst]=1
    result=$dst
}

# Generate a zipl section for a NixOS system configuration
addSection() {
    local path=$(readlink -f "$1")
    local name="$2"

    if ! test -e $path/kernel -a -e $path/initrd; then
        return
    fi

    copyToKernelsDir "$path/kernel"; kernel=$result
    copyToKernelsDir "$path/initrd"; initrd=$result

    extraParams="$(cat $path/kernel-params)"

    echo "[$name]"
    echo "  target = $target"
    echo "  image = $kernel"
    echo "  ramdisk = $initrd"
    echo "  parameters = \"init=$path/init $extraParams\""
    echo
}

tmpFile="$target/zipl.conf.tmp.$$"

cat > $tmpFile <<EOF
# Generated by NixOS, all changes will be lost on nixos-rebuild!
[defaultboot]
defaultmenu = menu1

EOF

# Build the menu section
{
    echo ":menu1"
    echo "  target = $target"
    echo "  timeout = $timeout"
    echo "  prompt = 1"
    echo "  default = 1"
    echo

    # Entry 1 is always the default
    menuIdx=1
    echo "  $menuIdx = nixos-default"
    menuIdx=$((menuIdx + 1))

    if [ "$numGenerations" -gt 0 ]; then
        for generation in $(
                (cd /nix/var/nix/profiles && ls -d system-*-link) \
                | sed 's/system-\([0-9]\+\)-link/\1/' \
                | sort -n -r \
                | head -n $numGenerations); do
            if [ $menuIdx -le 62 ]; then
                echo "  $menuIdx = nixos-$generation"
                menuIdx=$((menuIdx + 1))
            fi
        done
    fi

    echo
} >> $tmpFile

# Add the default section
addSection $default "nixos-default" >> $tmpFile

# Add generation sections
if [ "$numGenerations" -gt 0 ]; then
    menuIdx=2
    for generation in $(
            (cd /nix/var/nix/profiles && ls -d system-*-link) \
            | sed 's/system-\([0-9]\+\)-link/\1/' \
            | sort -n -r \
            | head -n $numGenerations); do
        if [ $menuIdx -le 62 ]; then
            link=/nix/var/nix/profiles/system-$generation-link
            addSection $link "nixos-$generation" >> $tmpFile
            menuIdx=$((menuIdx + 1))
        fi
    done
fi

mv -f $tmpFile $target/zipl.conf

# Install the boot record
zipl -c $target/zipl.conf

# Remove obsolete files from $target/nixos.
for fn in $target/nixos/*; do
    if ! test "${filesCopied[$fn]}" = 1; then
        echo "Removing no longer needed boot file: $fn"
        chmod +w -- "$fn"
        rm -rf -- "$fn"
    fi
done
