//===-- TileISelDAGToDAG.cpp - A Dag to Dag Inst Selector for Tile --------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file defines an instruction selector for the Tile target.
//
// First-light subset: relies on the tablegen-generated matcher plus the
// frameindex complex pattern. Custom selection of float, 64-bit multiply,
// network intrinsics and the PIC header is staged in over later phases.
//
//===----------------------------------------------------------------------===//

#include "Tile.h"
#include "TileSubtarget.h"
#include "TileTargetMachine.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "llvm/CodeGen/SelectionDAGNodes.h"
#include "llvm/Support/Debug.h"

using namespace llvm;

#define DEBUG_TYPE "tile-isel"
#define PASS_NAME "Tile DAG->DAG Pattern Instruction Selection"

namespace {

class TileDAGToDAGISel : public SelectionDAGISel {
public:
  explicit TileDAGToDAGISel(TileTargetMachine &tm) : SelectionDAGISel(tm) {}

  void Select(SDNode *N) override;

  // Return a target constant with the specified value, sized to the node type.
  SDValue getImm(const SDNode *Node, uint64_t Imm) {
    return CurDAG->getTargetConstant(Imm, SDLoc(Node), Node->getValueType(0));
  }

  bool SelectFI(SDValue N, SDValue &R1);

  bool SelectInlineAsmMemoryOperand(const SDValue &Op,
                                    InlineAsm::ConstraintCode ConstraintID,
                                    std::vector<SDValue> &OutOps) override;

// Include the pieces autogenerated from the target description.
#include "TileGenDAGISel.inc"
};

class TileDAGToDAGISelLegacy : public SelectionDAGISelLegacy {
public:
  static char ID;
  explicit TileDAGToDAGISelLegacy(TileTargetMachine &tm)
      : SelectionDAGISelLegacy(ID, std::make_unique<TileDAGToDAGISel>(tm)) {}
};

} // end anonymous namespace

char TileDAGToDAGISelLegacy::ID = 0;

INITIALIZE_PASS(TileDAGToDAGISelLegacy, DEBUG_TYPE, PASS_NAME, false, false)

bool TileDAGToDAGISel::SelectFI(SDValue N, SDValue &R1) {
  if (FrameIndexSDNode *FIN = dyn_cast<FrameIndexSDNode>(N)) {
    R1 = CurDAG->getTargetFrameIndex(FIN->getIndex(), MVT::i64);
    return true;
  }
  return false;
}

// f32 add/sub/mul: build the fsingle helper sequence GCC emits for addsf3/
// subsf3/mulsf3. add/sub share fsingle_addsub2 to combine the partial result
// with the operands; mul threads fsingle_mul2 through the second operand.
static SDNode *selectSingleFloatBinOp(SelectionDAG *DAG, SDNode *N) {
  SDLoc DL(N);
  unsigned Opc = N->getOpcode();
  SDValue A = N->getOperand(0);
  SDValue B = N->getOperand(1);
  unsigned Part1, Part2 = Tile::FSINGLE_ADDSUB2;
  switch (Opc) {
  case ISD::FADD:
    Part1 = Tile::FSINGLE_ADD1;
    break;
  case ISD::FSUB:
    Part1 = Tile::FSINGLE_SUB1;
    break;
  case ISD::FMUL:
    Part1 = Tile::FSINGLE_MUL1;
    Part2 = Tile::FSINGLE_MUL2;
    break;
  default:
    llvm_unreachable("selectSingleFloatBinOp: unexpected opcode");
  }
  SDNode *T0 = DAG->getMachineNode(Part1, DL, MVT::f32, A, B);
  SDNode *T1;
  if (Opc == ISD::FMUL)
    T1 = DAG->getMachineNode(Part2, DL, MVT::f32, SDValue(T0, 0), B);
  else
    T1 = DAG->getMachineNode(Part2, DL, MVT::f32, A, B, SDValue(T0, 0));
  SDValue T1V(T1, 0);
  SDNode *Flag = DAG->getMachineNode(Tile::FSINGLE_PACK1, DL, MVT::f32, T1V);
  return DAG->getMachineNode(Tile::FSINGLE_PACK2, DL, MVT::f32, T1V,
                             SDValue(Flag, 0));
}

// f64 add/sub: the fdouble helper sequence GCC emits for adddf3/subdf3.
static SDNode *selectDoubleFloatAddSub(SelectionDAG *DAG, SDNode *N) {
  SDLoc DL(N);
  SDValue A = N->getOperand(0);
  SDValue B = N->getOperand(1);
  unsigned FlagOpc = (N->getOpcode() == ISD::FSUB) ? Tile::FDOUBLE_SUB_FLAGS
                                                   : Tile::FDOUBLE_ADD_FLAGS;
  SDValue Zero = DAG->getRegister(Tile::ZERO, MVT::f64);
  SDNode *Min = DAG->getMachineNode(Tile::FDOUBLE_UNPACK_MIN, DL, MVT::f64, A, B);
  SDNode *Max = DAG->getMachineNode(Tile::FDOUBLE_UNPACK_MAX, DL, MVT::f64, A, B);
  SDNode *Flag = DAG->getMachineNode(FlagOpc, DL, MVT::f64, A, B);
  SDValue FlagV(Flag, 0);
  SDNode *Mid = DAG->getMachineNode(Tile::FDOUBLE_ADDSUB, DL, MVT::f64,
                                    SDValue(Min, 0), FlagV, SDValue(Max, 0));
  SDValue MidV(Mid, 0);
  SDNode *Res =
      DAG->getMachineNode(Tile::FDOUBLE_PACK1, DL, MVT::f64, MidV, FlagV);
  return DAG->getMachineNode(Tile::FDOUBLE_PACK2, DL, MVT::f64, MidV, Zero,
                             SDValue(Res, 0));
}

// f64 mul: the long fdouble/integer-partial-product sequence GCC emits for
// muldf3. Both operands are unpacked against zero, the 64x64 mantissa product
// is assembled from the 32-bit partial products, and fdouble_pack1/2 reapply
// the exponent and round.
static SDNode *selectDoubleFloatMul(SelectionDAG *DAG, SDNode *N) {
  SDLoc DL(N);
  SDValue A = N->getOperand(0);
  SDValue B = N->getOperand(1);
  SDValue C32 = DAG->getTargetConstant(32, DL, MVT::i64);
  SDValue Zero = DAG->getRegister(Tile::ZERO, MVT::f64);
  SDValue UA(
      DAG->getMachineNode(Tile::FDOUBLE_UNPACK_MAX, DL, MVT::f64, A, Zero), 0);
  SDValue UB(
      DAG->getMachineNode(Tile::FDOUBLE_UNPACK_MAX, DL, MVT::f64, B, Zero), 0);
  SDValue Flag(
      DAG->getMachineNode(Tile::FDOUBLE_MUL_FLAGS, DL, MVT::f64, A, B), 0);
  SDValue Low(DAG->getMachineNode(Tile::MUL_LU_LU, DL, MVT::i64, UA, UB), 0);
  SDValue Mid0(DAG->getMachineNode(Tile::MUL_HU_LU, DL, MVT::i64, UA, UB), 0);
  SDValue Mid(DAG->getMachineNode(Tile::MULA_HU_LU, DL, MVT::i64, Mid0, UB, UA),
              0);
  SDValue High0(DAG->getMachineNode(Tile::MUL_HU_HU, DL, MVT::i64, UA, UB), 0);
  SDValue MidL(DAG->getMachineNode(Tile::SHLI, DL, MVT::i64, Mid, C32), 0);
  SDValue MidR(DAG->getMachineNode(Tile::SHRUI, DL, MVT::i64, Mid, C32), 0);
  SDValue High1(DAG->getMachineNode(Tile::ADD, DL, MVT::i64, High0, MidR), 0);
  SDValue LowB(DAG->getMachineNode(Tile::ADD, DL, MVT::i64, Low, MidL), 0);
  SDValue Carry(DAG->getMachineNode(Tile::CMPLTU, DL, MVT::i64, LowB, MidL), 0);
  SDValue HighB(DAG->getMachineNode(Tile::ADD, DL, MVT::i64, High1, Carry), 0);
  SDValue Res(
      DAG->getMachineNode(Tile::FDOUBLE_PACK1, DL, MVT::f64, HighB, Flag), 0);
  return DAG->getMachineNode(Tile::FDOUBLE_PACK2, DL, MVT::f64, HighB, LowB,
                             Res);
}

// High 64 bits of a 64x64 multiply, assembled from the 32-bit partial products
// with explicit carry propagation, mirroring the 3.3-fork and GCC sequence. The
// carry handling was verified numerically against a 128-bit reference multiply
// over the 2^63 boundary, sign changes, and all-ones inputs. Signed uses the
// signed-high partial products (mul_hs_*) and arithmetic shifts; unsigned uses
// the unsigned forms (mul_hu_*) and logical shifts.
static SDNode *selectMulHigh64(SelectionDAG *DAG, SDNode *N) {
  SDLoc DL(N);
  bool Signed = N->getOpcode() == ISD::MULHS;
  SDValue A = N->getOperand(0);
  SDValue B = N->getOperand(1);
  SDValue C32 = DAG->getTargetConstant(32, DL, MVT::i64);

  unsigned MulHL = Signed ? Tile::MUL_HS_LU : Tile::MUL_HU_LU;
  unsigned MulHH = Signed ? Tile::MUL_HS_HS : Tile::MUL_HU_HU;
  unsigned ShrHi = Signed ? Tile::SHRSI : Tile::SHRUI;

  SDValue Low(DAG->getMachineNode(Tile::MUL_LU_LU, DL, MVT::i64, A, B), 0);
  SDValue MidA(DAG->getMachineNode(MulHL, DL, MVT::i64, A, B), 0);
  SDValue MidB(DAG->getMachineNode(MulHL, DL, MVT::i64, B, A), 0);
  SDValue High(DAG->getMachineNode(MulHH, DL, MVT::i64, A, B), 0);

  SDValue MidAL(DAG->getMachineNode(Tile::SHLI, DL, MVT::i64, MidA, C32), 0);
  SDValue MidBL(DAG->getMachineNode(Tile::SHLI, DL, MVT::i64, MidB, C32), 0);
  SDValue MidSum(DAG->getMachineNode(Tile::ADD, DL, MVT::i64, MidAL, MidBL), 0);
  SDValue LowSum(DAG->getMachineNode(Tile::ADD, DL, MVT::i64, Low, MidSum), 0);
  SDValue CarryMid(
      DAG->getMachineNode(Tile::CMPLTU, DL, MVT::i64, MidSum, MidAL), 0);
  SDValue CarryLow(
      DAG->getMachineNode(Tile::CMPLTU, DL, MVT::i64, LowSum, Low), 0);

  SDValue MidAH(DAG->getMachineNode(ShrHi, DL, MVT::i64, MidA, C32), 0);
  SDValue MidBH(DAG->getMachineNode(ShrHi, DL, MVT::i64, MidB, C32), 0);

  SDValue H1(DAG->getMachineNode(Tile::ADD, DL, MVT::i64, High, CarryMid), 0);
  SDValue H2(DAG->getMachineNode(Tile::ADD, DL, MVT::i64, CarryLow, MidAH), 0);
  SDValue H3(DAG->getMachineNode(Tile::ADD, DL, MVT::i64, H1, H2), 0);
  return DAG->getMachineNode(Tile::ADD, DL, MVT::i64, H3, MidBH);
}

// High 32 bits of a 32x32 multiply. The full product fits in 64 bits, so a
// single mul_lu_lu/mul_ls_ls (which read only the low 32 bits of each 64-bit
// register, so the i32 operands need no masking) followed by a shift of the
// high word is exact. The i32 operands are reinterpreted as i64 via sub_32 and
// the i32 result extracted the same way.
static SDNode *selectMulHigh32(SelectionDAG *DAG, SDNode *N) {
  SDLoc DL(N);
  bool Signed = N->getOpcode() == ISD::MULHS;
  SDValue C32 = DAG->getTargetConstant(32, DL, MVT::i64);
  SDValue Undef(
      DAG->getMachineNode(TargetOpcode::IMPLICIT_DEF, DL, MVT::i64), 0);
  SDValue A = DAG->getTargetInsertSubreg(Tile::sub_32, DL, MVT::i64, Undef,
                                         N->getOperand(0));
  SDValue B = DAG->getTargetInsertSubreg(Tile::sub_32, DL, MVT::i64, Undef,
                                         N->getOperand(1));
  unsigned MulOp = Signed ? Tile::MUL_LS_LS : Tile::MUL_LU_LU;
  unsigned ShrOp = Signed ? Tile::SHRSI : Tile::SHRUI;
  SDValue Prod(DAG->getMachineNode(MulOp, DL, MVT::i64, A, B), 0);
  SDValue Hi(DAG->getMachineNode(ShrOp, DL, MVT::i64, Prod, C32), 0);
  return DAG->getTargetExtractSubreg(Tile::sub_32, DL, MVT::i32, Hi).getNode();
}

void TileDAGToDAGISel::Select(SDNode *Node) {
  if (Node->isMachineOpcode()) {
    Node->setNodeId(-1);
    return;
  }

  SDLoc DL(Node);

  switch (Node->getOpcode()) {
  default:
    break;
  case ISD::FADD:
  case ISD::FSUB:
  case ISD::FMUL: {
    EVT VT = Node->getValueType(0);
    if (VT == MVT::f32) {
      ReplaceNode(Node, selectSingleFloatBinOp(CurDAG, Node));
      return;
    }
    if (VT == MVT::f64) {
      ReplaceNode(Node, Node->getOpcode() == ISD::FMUL
                            ? selectDoubleFloatMul(CurDAG, Node)
                            : selectDoubleFloatAddSub(CurDAG, Node));
      return;
    }
    break;
  }
  case ISD::MUL: {
    // TILE-Gx lacks a single 64-bit multiply. Build the product from the
    // 32x32 partial products: low*low, plus (high*low + low*high) << 32,
    // mirroring the GCC and 3.3-fork lowering. The i32 case is handled by the
    // mulx pattern, so only intercept i64 here.
    if (Node->getValueType(0) != MVT::i64)
      break;
    SDValue A = Node->getOperand(0);
    SDValue B = Node->getOperand(1);
    SDValue C32 = CurDAG->getTargetConstant(32, DL, MVT::i64);

    SDNode *T = CurDAG->getMachineNode(Tile::MUL_HU_LU, DL, MVT::i64, A, B);
    T = CurDAG->getMachineNode(Tile::MULA_HU_LU, DL, MVT::i64, SDValue(T, 0), B,
                               A);
    T = CurDAG->getMachineNode(Tile::SHLI, DL, MVT::i64, SDValue(T, 0), C32);
    ReplaceNode(Node, CurDAG->getMachineNode(Tile::MULA_LU_LU, DL, MVT::i64,
                                             SDValue(T, 0), B, A));
    return;
  }
  case ISD::MULHU:
  case ISD::MULHS: {
    EVT VT = Node->getValueType(0);
    if (VT == MVT::i64) {
      ReplaceNode(Node, selectMulHigh64(CurDAG, Node));
      return;
    }
    if (VT == MVT::i32) {
      ReplaceNode(Node, selectMulHigh32(CurDAG, Node));
      return;
    }
    break;
  }
  }

  SelectCode(Node);
}

bool TileDAGToDAGISel::SelectInlineAsmMemoryOperand(
    const SDValue &Op, InlineAsm::ConstraintCode ConstraintID,
    std::vector<SDValue> &OutOps) {
  assert(ConstraintID == InlineAsm::ConstraintCode::m &&
         "unexpected asm memory constraint");
  OutOps.push_back(Op);
  return false;
}

FunctionPass *llvm::createTileISelDag(TileTargetMachine &TM, CodeGenOptLevel) {
  return new TileDAGToDAGISelLegacy(TM);
}
