//===-- TileSubtarget.h - Define Subtarget for the Tile ---------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file declares the Tile specific subclass of TargetSubtargetInfo.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_LIB_TARGET_TILE_TILESUBTARGET_H
#define LLVM_LIB_TARGET_TILE_TILESUBTARGET_H

#include "TileFrameLowering.h"
#include "TileISelLowering.h"
#include "TileInstrInfo.h"
#include "TileSelectionDAGInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/MC/MCInstrItineraries.h"
#include <string>

#define GET_SUBTARGETINFO_HEADER
#include "TileGenSubtargetInfo.inc"

namespace llvm {
class StringRef;
class TargetMachine;

class TileSubtarget : public TileGenSubtargetInfo {
  virtual void anchor();

  InstrItineraryData InstrItins;
  TileInstrInfo InstrInfo;
  TileTargetLowering TLInfo;
  TileFrameLowering FrameLowering;
  TileSelectionDAGInfo TSInfo;

public:
  TileSubtarget(const StringRef &CPU, const StringRef &TuneCPU,
                const StringRef &FS, const TargetMachine &TM);

  TileSubtarget &initializeSubtargetDependencies(StringRef CPU,
                                                 StringRef TuneCPU,
                                                 StringRef FS);

  const TileInstrInfo *getInstrInfo() const override { return &InstrInfo; }
  const TileFrameLowering *getFrameLowering() const override {
    return &FrameLowering;
  }
  const TileRegisterInfo *getRegisterInfo() const override {
    return &InstrInfo.getRegisterInfo();
  }
  const TileTargetLowering *getTargetLowering() const override {
    return &TLInfo;
  }
  const TileSelectionDAGInfo *getSelectionDAGInfo() const override {
    return &TSInfo;
  }
  const InstrItineraryData *getInstrItineraryData() const override {
    return &InstrItins;
  }

  // ParseSubtargetFeatures - Parses features string setting specified subtarget
  // options.  Definition of function is auto generated by tblgen.
  void ParseSubtargetFeatures(StringRef CPU, StringRef TuneCPU, StringRef FS);
};

} // end namespace llvm

#endif // LLVM_LIB_TARGET_TILE_TILESUBTARGET_H
